AllCops:
  Exclude:
    - 'bin/**/*'
    - 'test/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'Gemfile'
    - 'spec/**/*'
    - 'lib/**/*'
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false